// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 11.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Lowis_Reports_Testing
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.HtmlControls;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public partial class UIMap
    {
        
        #region Properties
        public UILOWISmeinwessqalwUseWindow UILOWISmeinwessqalwUseWindow
        {
            get
            {
                if ((this.mUILOWISmeinwessqalwUseWindow == null))
                {
                    this.mUILOWISmeinwessqalwUseWindow = new UILOWISmeinwessqalwUseWindow();
                }
                return this.mUILOWISmeinwessqalwUseWindow;
            }
        }
        
        public UILOWISMEINWESSQALW01UWindow UILOWISMEINWESSQALW01UWindow
        {
            get
            {
                if ((this.mUILOWISMEINWESSQALW01UWindow == null))
                {
                    this.mUILOWISMEINWESSQALW01UWindow = new UILOWISMEINWESSQALW01UWindow();
                }
                return this.mUILOWISMEINWESSQALW01UWindow;
            }
        }
        
        public UIImportaNewWellModelFWindow UIImportaNewWellModelFWindow
        {
            get
            {
                if ((this.mUIImportaNewWellModelFWindow == null))
                {
                    this.mUIImportaNewWellModelFWindow = new UIImportaNewWellModelFWindow();
                }
                return this.mUIImportaNewWellModelFWindow;
            }
        }
        #endregion
        
        #region Fields
        private UILOWISmeinwessqalwUseWindow mUILOWISmeinwessqalwUseWindow;
        
        private UILOWISMEINWESSQALW01UWindow mUILOWISMEINWESSQALW01UWindow;
        
        private UIImportaNewWellModelFWindow mUIImportaNewWellModelFWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UILOWISmeinwessqalwUseWindow : WinWindow
    {
        
        public UILOWISmeinwessqalwUseWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "LOWIS: meinwessqalw (User: WFT\\hegdepr, Role: Administrators)";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("LOWIS: meinwessqalw (User: WFT\\hegdepr, Role: Administrators)");
            #endregion
        }
        
        #region Properties
        public UIItemClient UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemClient mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItemClient : WinClient
    {
        
        public UIItemClient(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.ClassName] = "Internet Explorer_Server";
            this.WindowTitles.Add("LOWIS: meinwessqalw (User: WFT\\hegdepr, Role: Administrators)");
            #endregion
        }
        
        #region Properties
        public UIFileCUsershegdeprcssDocument UIFileCUsershegdeprcssDocument
        {
            get
            {
                if ((this.mUIFileCUsershegdeprcssDocument == null))
                {
                    this.mUIFileCUsershegdeprcssDocument = new UIFileCUsershegdeprcssDocument(this);
                }
                return this.mUIFileCUsershegdeprcssDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIFileCUsershegdeprcssDocument mUIFileCUsershegdeprcssDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIFileCUsershegdeprcssDocument : HtmlDocument
    {
        
        public UIFileCUsershegdeprcssDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[HtmlDocument.PropertyNames.TagInstance] = "-1";
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = null;
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "C:/Users/hegdepr/csstore/11Sep201503124844/MEINWESSQALW/Demodb/ALLPRODS/csLift/LI" +
                "FTSRV/XHTML/SUBS/DHTML/PARAMETER.CHART.HTM";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "file://C:\\Users\\hegdepr\\csstore\\11Sep201503124844\\MEINWESSQALW\\Demodb\\ALLPRODS\\cs" +
                "Lift\\LIFTSRV\\XHTML\\SUBS\\DHTML\\PARAMETER.CHART.HTM";
            this.WindowTitles.Add("LOWIS: meinwessqalw (User: WFT\\hegdepr, Role: Administrators)");
            #endregion
        }
        
        #region Properties
        public HtmlEdit UIEPfwhEdit
        {
            get
            {
                if ((this.mUIEPfwhEdit == null))
                {
                    this.mUIEPfwhEdit = new HtmlEdit(this);
                    #region Search Criteria
                    this.mUIEPfwhEdit.SearchProperties[HtmlEdit.PropertyNames.Id] = "ePfwh";
                    this.mUIEPfwhEdit.FilterProperties[HtmlEdit.PropertyNames.Title] = null;
                    this.mUIEPfwhEdit.FilterProperties[HtmlEdit.PropertyNames.Class] = "clsFloatValue";
                    this.mUIEPfwhEdit.FilterProperties[HtmlEdit.PropertyNames.ControlDefinition] = "id=ePfwh class=clsFloatValue value=710.0";
                    this.mUIEPfwhEdit.FilterProperties[HtmlEdit.PropertyNames.TagInstance] = "1";
                    this.mUIEPfwhEdit.WindowTitles.Add("LOWIS: meinwessqalw (User: WFT\\hegdepr, Role: Administrators)");
                    #endregion
                }
                return this.mUIEPfwhEdit;
            }
        }
        #endregion
        
        #region Fields
        private HtmlEdit mUIEPfwhEdit;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UILOWISMEINWESSQALW01UWindow : WinWindow
    {
        
        public UILOWISMEINWESSQALW01UWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "LOWIS: MEINWESSQALW01 (User: WFT\\hegdepr, Role: Administrators)";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("LOWIS: MEINWESSQALW01 (User: WFT\\hegdepr, Role: Administrators)");
            #endregion
        }
        
        #region Properties
        public UIItemWindow UIItemWindow
        {
            get
            {
                if ((this.mUIItemWindow == null))
                {
                    this.mUIItemWindow = new UIItemWindow(this);
                }
                return this.mUIItemWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIItemWindow mUIItemWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItemWindow : WinWindow
    {
        
        public UIItemWindow(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlId] = "59392";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            this.WindowTitles.Add("LOWIS: MEINWESSQALW01 (User: WFT\\hegdepr, Role: Administrators)");
            #endregion
        }
        
        #region Properties
        public WinButton UIImportaNewWellModelFButton
        {
            get
            {
                if ((this.mUIImportaNewWellModelFButton == null))
                {
                    this.mUIImportaNewWellModelFButton = new WinButton(this);
                    #region Search Criteria
                    this.mUIImportaNewWellModelFButton.SearchProperties[WinButton.PropertyNames.Name] = "Import a New Well Model File";
                    this.mUIImportaNewWellModelFButton.WindowTitles.Add("LOWIS: MEINWESSQALW01 (User: WFT\\hegdepr, Role: Administrators)");
                    #endregion
                }
                return this.mUIImportaNewWellModelFButton;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mUIImportaNewWellModelFButton;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIImportaNewWellModelFWindow : WinWindow
    {
        
        public UIImportaNewWellModelFWindow()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Import a New Well Model File";
            this.SearchProperties[WinWindow.PropertyNames.ClassName] = "#32770";
            this.WindowTitles.Add("Import a New Well Model File");
            #endregion
        }
        
        #region Properties
        public UIItemClient1 UIItemClient
        {
            get
            {
                if ((this.mUIItemClient == null))
                {
                    this.mUIItemClient = new UIItemClient1(this);
                }
                return this.mUIItemClient;
            }
        }
        #endregion
        
        #region Fields
        private UIItemClient1 mUIItemClient;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIItemClient1 : WinClient
    {
        
        public UIItemClient1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinControl.PropertyNames.ClassName] = "Internet Explorer_Server";
            this.WindowTitles.Add("Import a New Well Model File");
            #endregion
        }
        
        #region Properties
        public UIImportWellModelFileDocument UIImportWellModelFileDocument
        {
            get
            {
                if ((this.mUIImportWellModelFileDocument == null))
                {
                    this.mUIImportWellModelFileDocument = new UIImportWellModelFileDocument(this);
                }
                return this.mUIImportWellModelFileDocument;
            }
        }
        #endregion
        
        #region Fields
        private UIImportWellModelFileDocument mUIImportWellModelFileDocument;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "11.0.60315.1")]
    public class UIImportWellModelFileDocument : HtmlDocument
    {
        
        public UIImportWellModelFileDocument(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.FilterProperties[HtmlDocument.PropertyNames.Title] = "Import Well Model File";
            this.FilterProperties[HtmlDocument.PropertyNames.AbsolutePath] = "C:/Users/hegdepr/csstore/15/MEINWESSQALW/Demodb/ALLPRODS/csLift/LIFTSRV/XHTML/COM" +
                "MON/DHTML/ImportWellModelFile.htm";
            this.FilterProperties[HtmlDocument.PropertyNames.PageUrl] = "file://C:\\Users\\hegdepr\\csstore\\15\\MEINWESSQALW\\Demodb\\ALLPRODS\\csLift\\LIFTSRV\\XH" +
                "TML\\COMMON\\DHTML\\ImportWellModelFile.htm";
            this.WindowTitles.Add("Import a New Well Model File");
            #endregion
        }
        
        #region Properties
        public HtmlFileInput UIBrowseaWellModelfileFileInput
        {
            get
            {
                if ((this.mUIBrowseaWellModelfileFileInput == null))
                {
                    this.mUIBrowseaWellModelfileFileInput = new HtmlFileInput(this);
                    #region Search Criteria
                    this.mUIBrowseaWellModelfileFileInput.SearchProperties[HtmlFileInput.PropertyNames.Id] = "pvFileName";
                    this.mUIBrowseaWellModelfileFileInput.SearchProperties[HtmlFileInput.PropertyNames.Name] = null;
                    this.mUIBrowseaWellModelfileFileInput.SearchProperties[HtmlFileInput.PropertyNames.LabeledBy] = null;
                    this.mUIBrowseaWellModelfileFileInput.FilterProperties[HtmlFileInput.PropertyNames.Title] = "Browse a Well Model file";
                    this.mUIBrowseaWellModelfileFileInput.FilterProperties[HtmlFileInput.PropertyNames.Class] = null;
                    this.mUIBrowseaWellModelfileFileInput.FilterProperties[HtmlFileInput.PropertyNames.ControlDefinition] = "id=pvFileName title=\"Browse a Well Model";
                    this.mUIBrowseaWellModelfileFileInput.FilterProperties[HtmlFileInput.PropertyNames.TagInstance] = "1";
                    this.mUIBrowseaWellModelfileFileInput.WindowTitles.Add("Import a New Well Model File");
                    #endregion
                }
                return this.mUIBrowseaWellModelfileFileInput;
            }
        }
        #endregion
        
        #region Fields
        private HtmlFileInput mUIBrowseaWellModelfileFileInput;
        #endregion
    }
}
